### ISSUE TITLE
Other dietary inputs

### ISSUE THREAD

**Issue by mgranberry** [tidepool-org/deprecated-data-model#19]
Fat and proteins also affect BGs, as does dietary fiber. While they are not as fast as for carbs, any record keeping utility should include the ability to log these as well.  I know from personal experience that a fatty 12oz will have an effect for as long as 12h if I don't cover it with a long and slow extended bolus.

**Comment by cheddar** [comment]
This is absolutely correct.  We'll definitely have to keep this in mind as we add the ability to store and maintain meal data.

Right now, we are merely extracting data from pumps and showing that.  Pumps generally just have a bolus wizard where you enter your carbohydrates and are then move on, so all we handle right now is carbs...

**Comment by cheddar** [comment]
Btw, we are going to retire this repository in favor of putting data-model stuff on the micro-site

https://github.com/tidepool-org/tidepool-org.github.io

Also, I think this would be a great issue to have in our central "hub" of issues.  That is at 

https://github.com/tidepool-org/hub

Unless you object, I'd like to re-create this issue in that repository and close this one.

**Comment by mgranberry** [comment]
No objections.
